name: PR Reminder

on:
  schedule:
    - cron: "0 0,5,8 * * *" # 아침 9시, 오후 2시, 오후 5시에 실행 (UTC 기준으로 설정해서 한국 시간에 맞춤)
  workflow_dispatch:

jobs:
  call-reusable-reminder:
    uses: 33-Auto/.github/.github/workflows/reusable-pr-reminder.yml@main
    secrets:
      # 해당 시크릿은 조직의 시크릿에 저장되어 있음
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
